[package]
name = "rust-nnet-macros"
version = "0.1.0"
authors = ["Ferris Tseng <ferristseng@gmail.com>"]

[lib]
name = "nnet_macros"

[dev-dependencies.rust-nnet]
path = "../rust-nnet"
version = "*"

[dev-dependencies]
csv = "*"
time = "*"
rustc-serialize = "*"