[package]
name = "rust-nnet"
version = "0.1.0"
authors = ["Ferris Tseng <ferristseng@gmail.com>"]

[lib]
name = "nnet"

[dependencies]
num = "*"
rand = "*"
num_cpus = "*"

[dependencies.threadpool]
version = "*"
features = ["scoped-pool"]